### PR TITLE
Gallery links (Contact profile-fields) - core/event/main_listener.php

### PR DESCRIPTION
**Pull request by K07H**
Fixed links to personal galleries in contact profile fields.

### CODE REVIEW

**Comment by satanasov** [comment]
OK. I see what you are doing here ... but I there was something wrong with this way.

Please check if the correct profile links are added in topics and in member list.

Wrong gallery links was why made it only work in profileview.

**Comment by K07H** [comment]
Alright I'm on it.

**Comment by K07H** [comment]
I checked all links (album IDs and URLs) to personal galleries in topics and memberlist and they are OK.
Only problem was that using relative URL was making memberlist template not able to generate proper links. I fixed it by concatenating the board url (I get it with the phpBB function "generate_board_url()") and the relative URL.
If you have more details about the wrong links you saw please tell me.

**Comment by K07H** [comment]
My bad... I just noticed links are wrong when someone posted multiple messages in a specific topic...
I'll just continue testing.

**Comment by satanasov** [comment]
This was the issue I was facing. This have an easy solution - make contact CPF and update on creation of the personal album. But this is going to be done for 1.2.1

**Comment by K07H** [comment]
So if I understand well I need to create a custom profile field when phpbbgallery is being installed (which will add some stuff in all the phpbb_profile_fields_data_*  tables basically)?
If yes I have to check how to do it programmatically :P (The only time I had to create custom profile fields I did it from the Admin Control Panel...).

**Pull request closed without merging**
