### PR TITLE
Fix get_uri() if board url contains ports, e.g. the board is running on ...

### PR DESCRIPTION
**Pull request by srt**
...a non-standard HTTP port

### CODE REVIEW

**Comment by srt** [comment]
Do you need any changes before you can merge this pull request?

**Comment by satanasov** [comment]
This does not fix the issue I have created this function for.

This is the BBCode generated by your PR: 

http://lab.anavaro.com/phpbb/phpbb/phpBB/phpbb/phpbb/phpBB/app.php/gallery/image/21

Should be http://lab.anavaro.com/phpbb/phpbb/phpBB/app.php/gallery/image/21

**Comment by srt** [comment]
@satanasov The link you have provided requires a login. Can you provide some more details on the original purpose of this function?

**Comment by satanasov** [comment]
Sorry. The idea behind the links was just to show the difference. 

Controller helper's function route create routes starting from root server level - /dir/to/phpbb/route

In same time build_board_url() creates http://domain.tld/dir/to/phpbb/

If you have meta_refresh (on upload) it refreshes to path that not exists.

The get_uri should create path like http://domain.tld/dir/to/phpbb/path

Hope you understand me. 

Please provide what is your problem.

**Comment by srt** [comment]
The problem was that we got "redirect to insecure page" errors before we applied our patch.

**Comment by satanasov** [comment]
Fixed the error today ... never encounter it untill now. This uses Force server vars ...

**Pull request closed without merging**
