### PR TITLE
Fast upload through posting.php

### PR DESCRIPTION
**Pull request by Wardormeur**
This is a proposed enhancement to allow a fast upload of pictures through the posting page.

### CODE REVIEW

**Comment by satanasov** [comment]
This is great. I will have to test it before add it.

But from what I see .. it will be verry good.

**Comment by Wardormeur** [comment]
to inform you : tests running atm to be sure that my fixes are correct (mostly whitespaces)
However, had to modify the .travis.yml conf in order to allow sudo (cf https://www.phpbb.com/community/viewtopic.php?f=461&t=2308251 )

**Comment by satanasov** [comment]
I faced that issue with other things.

**Comment by satanasov** [comment]
Hello.

Just got to your PR. It's nice.

However I think this needs to be optional. Admin should be able to allow it and the users should be able to disable it personally. Could you add the options in acp/config_module and in ucp?

**Comment by Wardormeur** [comment]
Im on it. However, i think this is more relevant to do it only for admin, and/or by forum. I'd consider it as a option that is like the "quick answer" one. In that way, i dont think that the user-option is smart nor logical : you ,as a user, dont disable smileys or shortcode; but the admin allows them accordingly to which forum they're supposed to be used.

**Comment by satanasov** [comment]
Yes, you are right. If you can add it as forum option, it will be even better.

**Comment by Wardormeur** [comment]
I actually only allowed through admin atm, i'm gonna need more time to get it to work with forums

**Comment by satanasov** [comment]
NO problem - I've added it for 1.2.1 milestone.

**Comment by Galixte** [comment]
Hi @Wardormeur, aurais-tu du temps pour finaliser ton PR ?

**Comment by Wardormeur** [comment]
Will do asap

**Comment by pokyto** [comment]
Dites moi si vous avez besoin d'aide! à plusieurs ce sera plus rapide!

**Pull request closed without merging**
